name: PlayerHeads
version: 3.0.0087
description: Drops a player's head when s/he dies, also mob heads
authors: [meiskam, zand]

main: org.shininet.bukkit.playerheads.PlayerHeads
database: false

commands:
  PlayerHeads:
    description: Spawn a playerhead or edit playerheads config
    aliases: ph
    
permissions:
  playerheads.*:
    description: Gives all PlayerHeads permissions
    default: false
    children:
      playerheads.config.*: true
      playerheads.spawn.*: true
      playerheads.update: true
      playerheads.rename: true
      playerheads.canbehead: true
      playerheads.canloosehead: true
      playerheads.canbeheadmob: true
      playerheads.update: true
      playerheads.alwaysbehead: true
      playerheads.alwaysbeheadmob: true
  playerheads.config.*:
    description: Allows user to edit, save, or reload configs
    default: op
    children:
      playerheads.config.get: true
      playerheads.config.set: true
  playerheads.config.get:
    description: Allows user to get configs
    default: op
  playerheads.config.set:
    description: Allows user to set or reload configs
    default: op
  playerheads.spawn.*:
    description: Spawn player heads
    default: op
    children:
      playerheads.spawn: true
      playerheads.spawn.forother: true
  playerheads.spawn:
    description: Spawn any player head
    default: op
    children:
      playerheads.spawn.own: true
  playerheads.spawn.own:
    description: Spawn your own head
    default: op
  playerheads.spawn.forother:
    description: Spawn a head into someone elses inventory
    default: op
  playerheads.rename:
    description: User can change the skin of the player head in their hand
    default: op
  playerheads.canbehead:
    description: User can remove heads from others
    default: true
  playerheads.canloosehead:
    description: User can have their head removed
    default: true
  playerheads.canbeheadmob:
    description: User can remove heads from mobs
    default: true
  playerheads.update:
    description: When update available, can view notice and manually update
    default: op
  playerheads.alwaysbehead:
    description: Ignore drop rate for player heads and drop 100% of the time
    default: false
  playerheads.alwaysbeheadmob:
    description: Ignore drop rate for mob heads and drop 100% of the time
    default: false
